/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthedEventsIndexRouteImport } from './routes/_authed/events/index'
import { Route as AuthedLogsIndexRouteImport } from './routes/_authed/logs/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedTemplatesIndexRouteImport } from './routes/_authed/templates/index'
import { Route as AuthedTemplatesNameRouteImport } from './routes/_authed/templates/$name'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedEventsIndexRoute = AuthedEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogsIndexRoute = AuthedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesIndexRoute = AuthedTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesNameRoute = AuthedTemplatesNameRouteImport.update({
  id: '/templates/$name',
  path: '/templates/$name',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/templates/$name': typeof AuthedTemplatesNameRoute
  '/events/': typeof AuthedEventsIndexRoute
  '/logs/': typeof AuthedLogsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/templates/': typeof AuthedTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
  '/templates/$name': typeof AuthedTemplatesNameRoute
  '/events': typeof AuthedEventsIndexRoute
  '/logs': typeof AuthedLogsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/templates': typeof AuthedTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authed/templates/$name': typeof AuthedTemplatesNameRoute
  '/_authed/events/': typeof AuthedEventsIndexRoute
  '/_authed/logs/': typeof AuthedLogsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/templates/': typeof AuthedTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/templates/$name'
    | '/events/'
    | '/logs/'
    | '/settings/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/templates/$name'
    | '/events'
    | '/logs'
    | '/settings'
    | '/templates'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/'
    | '/login/'
    | '/_authed/templates/$name'
    | '/_authed/events/'
    | '/_authed/logs/'
    | '/_authed/settings/'
    | '/_authed/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/events/': {
      id: '/_authed/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthedEventsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/logs/': {
      id: '/_authed/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthedLogsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates/': {
      id: '/_authed/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthedTemplatesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates/$name': {
      id: '/_authed/templates/$name'
      path: '/templates/$name'
      fullPath: '/templates/$name'
      preLoaderRoute: typeof AuthedTemplatesNameRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedTemplatesNameRoute: typeof AuthedTemplatesNameRoute
  AuthedEventsIndexRoute: typeof AuthedEventsIndexRoute
  AuthedLogsIndexRoute: typeof AuthedLogsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedTemplatesIndexRoute: typeof AuthedTemplatesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedTemplatesNameRoute: AuthedTemplatesNameRoute,
  AuthedEventsIndexRoute: AuthedEventsIndexRoute,
  AuthedLogsIndexRoute: AuthedLogsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedTemplatesIndexRoute: AuthedTemplatesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
